name: Reusable JSON Diff Workflow
on:
  workflow_call:
    inputs:
      variables:
        required: true
        type: string

jobs:
  json-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install and Configure JD
        run: |
          sudo wget -nv -O /usr/local/bin/jd https://github.com/josephburnett/jd/releases/download/v1.6.0/jd-amd64-linux
          sudo chmod +x /usr/local/bin/jd

      - name: Generate JSON Diff
        env:
          VARIABLES: ${{ inputs.variables }}
        run: |
          echo VARIABLES = $VARIABLES
          exit_code=0; git show remotes/origin/main~1:$VARIABLES 2> errors.txt || exit_code=$? && true
          if [ $exit_code -ne 0 ]; then
            echo "Creating empty json"
            touch oldjson
          else
            echo "Git show on existing json"
            git show $GITHUB_SHA~1:$VARIABLES > oldjson
          fi
          jd -yaml -set oldjson $VARIABLES | grep '^+' | sed -e 's/^+ //' > newjson
          echo "OLDJSON"
          cat oldjson
          echo "NEWJSON"
          cat newjson
