name: Process File Changes
on:
  workflow_call:
    inputs:
      file_paths:
        required: true
        type: string

jobs:
  process-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history

      - name: Process Files
        run: |
          file_paths=$(echo '${{ inputs.file_paths }}' | jq -r '.[]')
          for file in $file_paths; do
            echo "Processing file: $file"
            
            # Fetch the last commit hash where the file was changed, excluding the very last commit
            last_commit_hash=$(git log -2 --pretty=format:"%H" -- "$file" | tail -n 1)
            if [ -z "$last_commit_hash" ]; then
              echo "File not found in any previous commits, creating empty json."
              echo "{}" > oldjson
            else
              git show ${last_commit_hash}:$file > oldjson
              echo "Content of old JSON:"
              cat oldjson
            fi
            
            # Fetch the current version of the file
            git show HEAD:$file > newjson
            echo "Content of new JSON:"
            cat newjson

            # Additional commands to process oldjson and the current file can be added here
          done

          - name: Setup JD for JSON Diff
          run: |
            # Install JD and set permissions
            sudo wget -nv -O /usr/local/bin/jd https://github.com/josephburnett/jd/releases/download/v1.6.0/jd-amd64-linux
            sudo chmod +x /usr/local/bin/jd
        
      - name: Fetch Old and New JSON
        run: |
          # Assume OLDJSON and NEWJSON are already generated and saved as oldjson.json and newjson.json
          echo "OLDJSON"
          cat oldjson.json
          echo "NEWJSON"
          cat newjson.json
      
      - name: Use JD to Detect Changes
        run: |
          # Compare OLDJSON and NEWJSON
          jd --set oldjson.json newjson.json > diff.json
          echo "Differences Detected:"
          cat diff.json
      
          # Extract only additions (new blocks)
          additions=$(jd --set oldjson.json newjson.json | grep '^+' | sed -e 's/^+ //')
          echo "Additions:"
          echo "$additions"  