name: Reusable JSON Diff Workflow
on:
  workflow_call:
    inputs:
      variables:
        description: "Glob pattern for files to process"
        required: true
        type: string

jobs:
  json-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install and Configure JD
        run: |
          sudo wget -nv -O /usr/local/bin/jd https://github.com/josephburnett/jd/releases/download/v1.6.0/jd-amd64-linux
          sudo chmod +x /usr/local/bin/jd

      - name: Generate JSON Diff
        env:
          VARIABLES: ${{ inputs.variables }}
        run: |
          echo "Checking for file: $VARIABLES"
          last_commit_hash=$(git log -1 --pretty=format:"%H" -- "$VARIABLES")
          if [ -z "$last_commit_hash" ]; then
            echo "File not found in any previous commits, creating empty json."
            touch oldjson
          else
            echo "Found file in commit $last_commit_hash"
            git show ${last_commit_hash}:$VARIABLES > oldjson
            echo "Content of old JSON:"
            cat oldjson
          fi
          jd -yaml -set oldjson $VARIABLES | grep '^+' | sed -e 's/^+ //' > newjson
          echo "OLDJSON"
          cat oldjson
          echo "NEWJSON"
          cat newjson
