name: Reusable JSON Diff Workflow
on:
  workflow_call:
    inputs:
      file_paths:
        description: "JSON array of file paths to process"
        required: true
        type: string

jobs:
  json-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Process Each File
        run: |
          file_paths=$(echo '${{ inputs.file_paths }}' | jq -r '.[]')
          for file in $file_paths; do
            echo "Processing file: $file"
            last_commit_hash=$(git log -1 --pretty=format:"%H" -- "$file")
            if [ -z "$last_commit_hash" ]; then
              echo "File not found in any previous commits, creating empty json."
              echo "{}" > oldjson
            else
              git show ${last_commit_hash}:$file > oldjson
              echo "Content of old JSON:"
              cat oldjson
            fi
            # Additional commands to process oldjson and the current file
          done
