name: Process File Changes with PowerShell Diff

on:
  workflow_call:
    inputs:
      file_paths:
        required: true
        type: string

jobs:
  process-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git diff

      - name: Prepare JSON Files for Diff
        run: |
          mkdir -p ./json-files
          echo "Input file paths: ${{ inputs.file_paths }}"
          file_paths=$(echo '${{ inputs.file_paths }}' | jq -r '.[]')
          for file in $file_paths; do
            echo "Processing file: $file"

            is_added=$(git diff-tree --no-commit-id --name-only --diff-filter=A -r HEAD -- "$file" | wc -l)
            if [ "$is_added" -eq 1 ]; then
              echo "{}" > "./json-files/$(basename "$file")_old.json"
              git show HEAD:"$file" > "./json-files/$(basename "$file")_new.json"
            else
              last_commit_hash=$(git log -2 --pretty=format:"%H" -- "$file" | tail -n 1)
              if [ -z "$last_commit_hash" ]; then
                echo "{}" > "./json-files/$(basename "$file")_old.json"
              else
                git show ${last_commit_hash}:"$file" > "./json-files/$(basename "$file")_old.json"
              fi
              git show HEAD:"$file" > "./json-files/$(basename "$file")_new.json"
            fi

            echo "Content of old JSON:"
            cat "./json-files/$(basename "$file")_old.json"
            echo "Content of new JSON:"
            cat "./json-files/$(basename "$file")_new.json"
          done

      - name: Diff JSON Files with PowerShell
        shell: pwsh
        run: |
          $jsonPath = "./json-files"
          $files = Get-ChildItem -Path $jsonPath -Filter "*_old.json" | ForEach-Object {
              $_.FullName -replace "_old.json", ""
          }

          foreach ($file in $files) {
              $oldFile = "${file}_old.json"
              $newFile = "${file}_new.json"
              $outputFile = "${file}_diff.json"

              # Load JSON files
              $json1 = Get-Content -Path $oldFile -Raw | ConvertFrom-Json
              $json2 = Get-Content -Path $newFile -Raw | ConvertFrom-Json

              # Initialize an array to store the differences
              $diffResults = @()

              # Ensure the files have the same number of entries
              if ($json1.Count -ne $json2.Count) {
                  Write-Host "Error: Input files do not have the same number of entries."
                  exit 1
              }

              # Compare objects
              for ($i = 0; $i -lt $json1.Count; $i++) {
                  $item1 = $json1[$i]
                  $item2 = $json2[$i]

                  # Initialize a counter for changes
                  $changeCount = 0

                  # Prepare a diff entry
                  $diffEntry = [PSCustomObject]@{
                      ApplicationName               = $item1.ApplicationName
                      RoleGroupName                 = $item1.RoleGroupName
                      RoleGroupOwners               = $item1.RoleGroupOwners
                      TechnicalGroups               = $item1.TechnicalGroups
                      NestRoleGroupInTechnicalGroups = $item1.NestRoleGroupInTechnicalGroups
                      AccessReviewEnabled           = $item1.AccessReviewEnabled
                  }

                  # Compare RoleGroupOwners
                  $newRoleGroupOwners = @($item2.RoleGroupOwners | Where-Object { $_ -notin $item1.RoleGroupOwners })
                  if ($newRoleGroupOwners.Count -gt 0) {
                      $diffEntry.RoleGroupOwners = $newRoleGroupOwners
                      $changeCount++
                  }

                  # Compare TechnicalGroups
                  $newTechnicalGroups = @($item2.TechnicalGroups | Where-Object { $_ -notin $item1.TechnicalGroups })
                  if ($newTechnicalGroups.Count -gt 0) {
                      $diffEntry.TechnicalGroups = $newTechnicalGroups
                      $changeCount++
                  }

                  # Compare other fields
                  if ($item1.NestRoleGroupInTechnicalGroups -ne $item2.NestRoleGroupInTechnicalGroups) {
                      $diffEntry.NestRoleGroupInTechnicalGroups = $item2.NestRoleGroupInTechnicalGroups
                      $changeCount++
                  }
                  if ($item1.AccessReviewEnabled -ne $item2.AccessReviewEnabled) {
                      $diffEntry.AccessReviewEnabled = $item2.AccessReviewEnabled
                      $changeCount++
                  }

                  # Decide what to include in the output
                  if ($changeCount -gt 1) {
                      $diffResults += $item2
                  } elseif ($changeCount -eq 1) {
                      $diffResults += $diffEntry
                  }
              }

              # Save differences to file
              $diffResults | ConvertTo-Json -Depth 10 | Set-Content -Path $outputFile
              Write-Host "Diff saved to $outputFile"
          }

      - name: Upload JSON Diff Files
        uses: actions/upload-artifact@v4
        with:
          name: newjson-files
          path: ./json-files/*_diff.json
