name: 'Get changed files'
on:
  workflow_call:
    inputs:
      separator:
        description: 'Separator for the changed files'
        required: true
        type: string
      files:
        description: 'Files to check for changes'
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      # Check out Repository
      - name: Check out Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          separator: ${{ inputs.separator }}
          files: ${{ inputs.files }}

      - name: List all changed files
        id: matrix
        run: |
          printf ${{ steps.changed-files.outputs.all_changed_files }}|jq -R -s 'split(",")' -c > matrixjson
          echo "value=`cat matrixjson`" >> $GITHUB_OUTPUT
      
      # Log the output
      - name: Log all changed files
        run: |
          echo "All changed files: "
          cat matrixjson

      - name: Retrieve GitHub context for debugging later
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
